name: 测试

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: 设置Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    
    - name: 代码格式检查 (Linux only)
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
      run: |
        black --check src/
        isort --check-only src/
        flake8 src/
    
    - name: 类型检查 (Linux only)
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
      run: |
        mypy src/treer_sso_sdk/
    
    - name: 运行测试
      run: |
        pytest tests/ -v --cov=src/treer_sso_sdk --cov-report=xml
    
    - name: 测试包导入
      run: |
        python -c "import treer_sso_sdk; print(f'包版本: {treer_sso_sdk.__version__}')"
        python -c "from treer_sso_sdk import SSOConfig; config = SSOConfig('test', 'test'); print('✓ 配置测试通过')"
    
    - name: 上传覆盖率报告
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella 